### PR TITLE
A few small changes/refactors

### PR DESCRIPTION
**Pull request by briandipalma**

### CODE REVIEW

**Comment by RMcNeely** [comment]
Hey Brian, thanks for the PR, now that we've got [v0.0.3](https://github.com/ChartIQ/Charting-Library---React-Seed-Project/tree/v0.0.3) merged into master we'll be taking a look at this soon.

**Comment by briandipalma** [comment]
Cool, thanks @RMcNeely

**Comment by arbaaz** [comment]
I was not able to create an issue so posting here.

https://github.com/ChartIQ/Charting-Library---React-Seed-Project/blob/master/src/containers/chartContainer.js#L125

This action doesn't exist in chartActions.

**Comment by RMcNeely** [comment]
Hey @briandipalma sorry for the delay. We're trying to switch this project over to using a GitFlow branching strategy and won't be committing directly to master. Can I get you to change your target branch to develop and I'll start working thru it.

**Comment by appjitsu** [comment]
since we cant post issues...

i get nothing but errors when i try to run the project

image

**Comment by briandipalma** [comment]
@RMcNeely sorry for the massive delay, I've pointed it towards develop.

**Pull request closed without merging**
